# Example Gitaly configuration file.
# For Gitaly documentation, see https://docs.gitlab.com/ee/administration/gitaly/.

hooks_enabled = false
bin_dir = "/usr/bin"
listen_addr = "0.0.0.0:9999"

[git]
use_bundled_binaries = true

[[storage]]
name = "gitaly1"
path = "/var/lib/gitlab/repositories"

[hooks]

[gitlab]
url = "https://example.com"
# url = "http://0.0.0.0:9090"
secret = "secret"
