# Example Gitaly configuration file.
# For Gitaly documentation, see https://docs.gitlab.com/ee/administration/gitaly/.

hooks_enabled = false
bin_dir = "/usr/bin"
listen_addr = "0.0.0.0:9999"

[git]
use_bundled_binaries = true

[[storage]]
name = "default"
path = "/var/lib/gitlab/repositories"

[hooks]

[gitlab]
url = "http+unix://%2Frun%2Fgitlab%2Fgitlab-workhorse.socket"
secret = ""
