services:

  postgres:
    image: postgres:15.4
    container_name: postgres_db
    environment:
      POSTGRES_USER: hades
      POSTGRES_PASSWORD: hades
      POSTGRES_DB: hades
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  gitaly:
    image: alpinelinux/gitaly:17.6.2
    environment:
      - GITALY_TESTING_NO_GIT_HOOKS=true
    volumes:
      - /var/lib/gitlab:/var/lib/gitlab
      - ./config.toml:/etc/gitlab-gitaly/config.toml
    entrypoint: ["gitaly"]
    command: ["serve", "/etc/gitlab-gitaly/config.toml"]
    ports:
      - "9999:9999"

  # gitaly2:
  #   image: alpinelinux/gitaly:17.6.2
  #   environment:
  #     - GITALY_TESTING_NO_GIT_HOOKS=true
  #   volumes:
  #     - /var/lib/gitlab2:/var/lib/gitlab
  #     - ./config.toml:/etc/gitlab-gitaly/config.toml
  #   entrypoint: ["gitaly"]
  #   command: ["serve", "/etc/gitlab-gitaly/config.toml"]
  #   ports:
  #     - "9998:9999"

  praefect:
    image: alpinelinux/gitaly:17.6.2
    command: ["/bin/sh", "-c", "/usr/local/bin/praefect -config /etc/gitaly/praefect.toml sql-migrate && /usr/local/bin/praefect -config /etc/gitaly/praefect.toml"]
    ports:
      - "8075:8075"
    volumes:
      - ./praefect.toml:/etc/gitaly/praefect.toml
    depends_on:
      - postgres
      - gitaly

volumes:
  postgres_data:
  pgadmin:
  cache:
