services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    tty: true
    restart: unless-stopped

  postgres:
    image: postgres:15.4
    container_name: postgres_db
    environment:
      POSTGRES_USER: hades
      POSTGRES_PASSWORD: hades
      POSTGRES_DB: hades
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  gitaly:
    image: alpinelinux/gitaly:17.6.2
    container_name: gitaly
    # environment:
      # - GITALY_TESTING_NO_GIT_HOOKS=true
    volumes:
      - /var/lib/gitlab:/var/lib/gitlab
      - ./config.toml:/etc/gitlab-gitaly/config.toml
    entrypoint: ["gitaly"]
    command: ["serve", "/etc/gitlab-gitaly/config.toml"]
    network_mode: host
    ports:
      - "9999:9999"

volumes:
  postgres_data:
  pgadmin:
  cache:
