package telemetry

import "go.opentelemetry.io/otel/metric"

// Metric instruments. All are initialised by InitMetrics (called from Setup).
// Callers import this package and use the variables directly.
//
// Prometheus naming conventions applied by the OTel exporter:
//   - dots → underscores
//   - counters gain _total suffix
//   - histograms gain _bucket / _sum / _count suffixes
//   - unit "By" appends _bytes if the name does not already end with _bytes
//   - duration metrics intentionally omit unit string (the _ms suffix is enough)
var (
	// Prometheus: hades_upload_requests_total{status="ok|error"}
	UploadRequests metric.Int64Counter
	// Prometheus: hades_upload_duration_ms_{bucket,sum,count}
	UploadLatency metric.Float64Histogram
	// Prometheus: hades_upload_proto_bytes_{bucket,sum,count}
	UploadProtoBytes metric.Int64Histogram
	// Prometheus: hades_upload_file_count_{bucket,sum,count}
	UploadFileCount metric.Int64Histogram
	// Prometheus: hades_upload_alloc_bytes_{bucket,sum,count}  - full request
	UploadAllocBytes metric.Int64Histogram
	// Prometheus: hades_upload_gitaly_alloc_bytes_{bucket,sum,count}  - Gitaly write phase only
	UploadGitalyAllocBytes metric.Int64Histogram
	// Prometheus: hades_upload_gc_runs_{bucket,sum,count}  - GC cycles triggered per upload
	UploadGCRuns metric.Int64Histogram
	// Prometheus: hades_upload_gc_pause_ms_{bucket,sum,count}  - GC STW pause time per upload
	UploadGCPauseMs metric.Float64Histogram

	// Prometheus: hades_download_requests_total{status="ok|error"}
	DownloadRequests metric.Int64Counter
	// Prometheus: hades_download_duration_ms_{bucket,sum,count}
	DownloadLatency metric.Float64Histogram
	// Prometheus: hades_download_proto_bytes_{bucket,sum,count}
	DownloadProtoBytes metric.Int64Histogram
	// Prometheus: hades_download_alloc_bytes_{bucket,sum,count}  - full request
	DownloadAllocBytes metric.Int64Histogram
	// Prometheus: hades_download_gitaly_alloc_bytes_{bucket,sum,count}  - blob-fetch phase only
	DownloadGitalyAllocBytes metric.Int64Histogram
	// Prometheus: hades_download_gc_runs_{bucket,sum,count}
	DownloadGCRuns metric.Int64Histogram
	// Prometheus: hades_download_gc_pause_ms_{bucket,sum,count}
	DownloadGCPauseMs metric.Float64Histogram

	// Prometheus: hades_sdk_jobs_enqueued_total{module="..."}
	SDKJobsEnqueued metric.Int64Counter
	// Prometheus: hades_sdk_jobs_completed_total{status="succeeded|failed|dead",language="..."}
	SDKJobsCompleted metric.Int64Counter
	// Prometheus: hades_sdk_job_duration_ms_{bucket,sum,count}{language="..."}  - full job
	SDKJobDuration metric.Float64Histogram
	// Prometheus: hades_sdk_queue_depth
	SDKQueueDepth metric.Int64UpDownCounter
	// Prometheus: hades_sdk_proto_bytes_{bucket,sum,count}  - total proto bytes on disk per job
	SDKProtoBytes metric.Int64Histogram
	// Prometheus: hades_sdk_output_bytes_{bucket,sum,count}  - generated bytes uploaded to S3
	SDKOutputBytes metric.Int64Histogram
	// Prometheus: hades_sdk_alloc_bytes_{bucket,sum,count}  - full job alloc
	SDKAllocBytes metric.Int64Histogram
	// Prometheus: hades_sdk_stream_duration_ms_{bucket,sum,count}
	SDKStreamDurationMs metric.Float64Histogram
	// Prometheus: hades_sdk_stream_alloc_bytes_{bucket,sum,count}
	SDKStreamAllocBytes metric.Int64Histogram
	// Prometheus: hades_sdk_gen_duration_ms_{bucket,sum,count}
	SDKGenDurationMs metric.Float64Histogram
	// Prometheus: hades_sdk_gen_alloc_bytes_{bucket,sum,count}
	SDKGenAllocBytes metric.Int64Histogram
	// Prometheus: hades_sdk_s3_duration_ms_{bucket,sum,count}
	SDKS3DurationMs metric.Float64Histogram
	// Prometheus: hades_sdk_s3_alloc_bytes_{bucket,sum,count}
	SDKS3AllocBytes metric.Int64Histogram
	// Prometheus: hades_sdk_gc_runs_{bucket,sum,count}
	SDKGCRuns metric.Int64Histogram
	// Prometheus: hades_sdk_gc_pause_ms_{bucket,sum,count}
	SDKGCPauseMs metric.Float64Histogram
)

// InitMetrics creates all named instruments against the global meter.
// It is called automatically by Setup; do not call it manually.
func InitMetrics() error {
	m := Meter("hades")
	var err error

	if UploadRequests, err = m.Int64Counter(
		"hades.upload.requests",
		metric.WithDescription("Total upload RPC calls"),
	); err != nil {
		return err
	}

	if UploadLatency, err = m.Float64Histogram(
		"hades.upload.duration_ms",
		metric.WithDescription("Upload handler end-to-end latency in ms"),
		metric.WithExplicitBucketBoundaries(5, 25, 100, 500, 1000, 5000),
	); err != nil {
		return err
	}

	if UploadProtoBytes, err = m.Int64Histogram(
		"hades.upload.proto_bytes",
		metric.WithDescription("Total proto file bytes written to Gitaly per upload call"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(1024, 10240, 102400, 1048576, 10485760, 104857600),
	); err != nil {
		return err
	}

	if UploadFileCount, err = m.Int64Histogram(
		"hades.upload.file_count",
		metric.WithDescription("Number of proto files per upload call"),
		metric.WithExplicitBucketBoundaries(1, 5, 10, 25, 50, 100, 250),
	); err != nil {
		return err
	}

	if UploadAllocBytes, err = m.Int64Histogram(
		"hades.upload.alloc_bytes",
		metric.WithDescription("Heap bytes allocated during each upload call (TotalAlloc delta, full request)"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(65536, 524288, 2097152, 8388608, 33554432, 134217728),
	); err != nil {
		return err
	}

	if UploadGitalyAllocBytes, err = m.Int64Histogram(
		"hades.upload.gitaly_alloc_bytes",
		metric.WithDescription("Heap bytes allocated during the Gitaly write phase of each upload"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(65536, 524288, 2097152, 8388608, 33554432, 134217728),
	); err != nil {
		return err
	}

	if UploadGCRuns, err = m.Int64Histogram(
		"hades.upload.gc_runs",
		metric.WithDescription("Number of GC cycles triggered during each upload call"),
		metric.WithExplicitBucketBoundaries(0, 1, 2, 3, 5, 10),
	); err != nil {
		return err
	}

	if UploadGCPauseMs, err = m.Float64Histogram(
		"hades.upload.gc_pause_ms",
		metric.WithDescription("Total GC stop-the-world pause time in ms during each upload call"),
		metric.WithExplicitBucketBoundaries(0, 0.05, 0.1, 0.5, 1, 5, 10, 50),
	); err != nil {
		return err
	}

	if DownloadRequests, err = m.Int64Counter(
		"hades.download.requests",
		metric.WithDescription("Total download RPC calls"),
	); err != nil {
		return err
	}

	if DownloadLatency, err = m.Float64Histogram(
		"hades.download.duration_ms",
		metric.WithDescription("Download handler end-to-end latency in ms"),
		metric.WithExplicitBucketBoundaries(5, 25, 100, 500, 1000, 5000),
	); err != nil {
		return err
	}

	if DownloadProtoBytes, err = m.Int64Histogram(
		"hades.download.proto_bytes",
		metric.WithDescription("Total proto file bytes read from Gitaly per download call"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(1024, 10240, 102400, 1048576, 10485760, 104857600),
	); err != nil {
		return err
	}

	if DownloadAllocBytes, err = m.Int64Histogram(
		"hades.download.alloc_bytes",
		metric.WithDescription("Heap bytes allocated during each download call (TotalAlloc delta, full request)"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(65536, 524288, 2097152, 8388608, 33554432, 134217728),
	); err != nil {
		return err
	}

	if DownloadGitalyAllocBytes, err = m.Int64Histogram(
		"hades.download.gitaly_alloc_bytes",
		metric.WithDescription("Heap bytes allocated during the Gitaly blob-fetch phase of each download"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(65536, 524288, 2097152, 8388608, 33554432, 134217728),
	); err != nil {
		return err
	}

	if DownloadGCRuns, err = m.Int64Histogram(
		"hades.download.gc_runs",
		metric.WithDescription("Number of GC cycles triggered during each download call"),
		metric.WithExplicitBucketBoundaries(0, 1, 2, 3, 5, 10),
	); err != nil {
		return err
	}

	if DownloadGCPauseMs, err = m.Float64Histogram(
		"hades.download.gc_pause_ms",
		metric.WithDescription("Total GC stop-the-world pause time in ms during each download call"),
		metric.WithExplicitBucketBoundaries(0, 0.05, 0.1, 0.5, 1, 5, 10, 50),
	); err != nil {
		return err
	}

	if SDKJobsEnqueued, err = m.Int64Counter(
		"hades.sdk.jobs_enqueued",
		metric.WithDescription("Total SDK jobs enqueued (one per generator per upload)"),
	); err != nil {
		return err
	}

	if SDKJobsCompleted, err = m.Int64Counter(
		"hades.sdk.jobs_completed",
		metric.WithDescription("Total SDK jobs finished - label status: succeeded|failed|dead"),
	); err != nil {
		return err
	}

	if SDKJobDuration, err = m.Float64Histogram(
		"hades.sdk.job_duration_ms",
		metric.WithDescription("SDK job wall time from claim to completion in ms"),
		metric.WithExplicitBucketBoundaries(100, 500, 1000, 5000, 15000, 60000),
	); err != nil {
		return err
	}

	if SDKQueueDepth, err = m.Int64UpDownCounter(
		"hades.sdk.queue_depth",
		metric.WithDescription("Approximate number of pending SDK jobs"),
	); err != nil {
		return err
	}

	if SDKProtoBytes, err = m.Int64Histogram(
		"hades.sdk.proto_bytes",
		metric.WithDescription("Total proto bytes on disk (streamed from Gitaly) per SDK job"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(1024, 10240, 102400, 1048576, 10485760, 104857600),
	); err != nil {
		return err
	}

	if SDKOutputBytes, err = m.Int64Histogram(
		"hades.sdk.output_bytes",
		metric.WithDescription("Total generated file bytes uploaded to S3 per SDK job"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(1024, 10240, 102400, 1048576, 10485760, 104857600),
	); err != nil {
		return err
	}

	if SDKAllocBytes, err = m.Int64Histogram(
		"hades.sdk.alloc_bytes",
		metric.WithDescription("Heap bytes allocated during each SDK job (TotalAlloc delta, full job)"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(65536, 524288, 2097152, 8388608, 33554432, 134217728),
	); err != nil {
		return err
	}

	if SDKStreamDurationMs, err = m.Float64Histogram(
		"hades.sdk.stream_duration_ms",
		metric.WithDescription("Duration of the Gitaly blob-stream phase per SDK job in ms"),
		metric.WithExplicitBucketBoundaries(5, 25, 100, 500, 1000, 5000),
	); err != nil {
		return err
	}

	if SDKStreamAllocBytes, err = m.Int64Histogram(
		"hades.sdk.stream_alloc_bytes",
		metric.WithDescription("Heap bytes allocated during the Gitaly stream phase per SDK job"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(65536, 524288, 2097152, 8388608, 33554432, 134217728),
	); err != nil {
		return err
	}

	if SDKGenDurationMs, err = m.Float64Histogram(
		"hades.sdk.gen_duration_ms",
		metric.WithDescription("Duration of the protoc code-generation phase per SDK job in ms"),
		metric.WithExplicitBucketBoundaries(100, 500, 1000, 5000, 15000, 60000),
	); err != nil {
		return err
	}

	if SDKGenAllocBytes, err = m.Int64Histogram(
		"hades.sdk.gen_alloc_bytes",
		metric.WithDescription("Heap bytes allocated during the protoc generation phase per SDK job"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(65536, 524288, 2097152, 8388608, 33554432, 134217728),
	); err != nil {
		return err
	}

	if SDKS3DurationMs, err = m.Float64Histogram(
		"hades.sdk.s3_duration_ms",
		metric.WithDescription("Duration of the S3 upload phase per SDK job in ms"),
		metric.WithExplicitBucketBoundaries(25, 100, 500, 1000, 5000, 15000),
	); err != nil {
		return err
	}

	if SDKS3AllocBytes, err = m.Int64Histogram(
		"hades.sdk.s3_alloc_bytes",
		metric.WithDescription("Heap bytes allocated during the S3 upload phase per SDK job"),
		metric.WithUnit("By"),
		metric.WithExplicitBucketBoundaries(65536, 524288, 2097152, 8388608, 33554432, 134217728),
	); err != nil {
		return err
	}

	if SDKGCRuns, err = m.Int64Histogram(
		"hades.sdk.gc_runs",
		metric.WithDescription("Number of GC cycles triggered during each SDK job"),
		metric.WithExplicitBucketBoundaries(0, 1, 2, 3, 5, 10),
	); err != nil {
		return err
	}

	if SDKGCPauseMs, err = m.Float64Histogram(
		"hades.sdk.gc_pause_ms",
		metric.WithDescription("Total GC stop-the-world pause time in ms during each SDK job"),
		metric.WithExplicitBucketBoundaries(0, 0.05, 0.1, 0.5, 1, 5, 10, 50),
	); err != nil {
		return err
	}

	return nil
}
