import React from 'react';

interface IconProps {
  size?: number;
  style?: React.CSSProperties;
  className?: string;
}

const Icon: React.FC<IconProps & { children: React.ReactNode }> = ({ size = 16, children, style, className }) => (
  <svg width={size} height={size} viewBox="0 0 16 16" fill="none"
    xmlns="http://www.w3.org/2000/svg" style={{ flexShrink: 0, ...style }}
    className={className}>
    {children}
  </svg>
);

export const IconHome: React.FC<IconProps> = (p) => <Icon {...p}><path d="M8 1L1 7v8h5v-4h4v4h5V7L8 1z" stroke="currentColor" strokeWidth="1.2" strokeLinejoin="round" fill="none"/></Icon>;
export const IconSearch: React.FC<IconProps> = (p) => <Icon {...p}><circle cx="7" cy="7" r="4.5" stroke="currentColor" strokeWidth="1.2"/><line x1="10.5" y1="10.5" x2="14.5" y2="14.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconBox: React.FC<IconProps> = (p) => <Icon {...p}><polyline points="2,4 8,7 14,4" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><path d="M2 4l6 3 6-3v8l-6 3-6-3V4z" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><line x1="8" y1="7" x2="8" y2="15" stroke="currentColor" strokeWidth="1.2"/></Icon>;
export const IconBuilding: React.FC<IconProps> = (p) => <Icon {...p}><rect x="1" y="4" width="9" height="11" stroke="currentColor" strokeWidth="1.2" fill="none"/><path d="M10 7h4v8h-4" stroke="currentColor" strokeWidth="1.2" fill="none"/><rect x="3" y="7" width="2" height="2" stroke="currentColor" strokeWidth="1" fill="none"/><rect x="6" y="7" width="2" height="2" stroke="currentColor" strokeWidth="1" fill="none"/><rect x="3" y="11" width="2" height="2" stroke="currentColor" strokeWidth="1" fill="none"/><rect x="6" y="11" width="2" height="2" stroke="currentColor" strokeWidth="1" fill="none"/><rect x="4" y="13" width="2" height="2" stroke="currentColor" strokeWidth="1.2" fill="none"/></Icon>;
export const IconGear: React.FC<IconProps> = (p) => <Icon {...p}><circle cx="8" cy="8" r="2.5" stroke="currentColor" strokeWidth="1.2"/><path d="M8 1v2M8 13v2M1 8h2M13 8h2M2.93 2.93l1.41 1.41M11.66 11.66l1.41 1.41M2.93 13.07l1.41-1.41M11.66 4.34l1.41-1.41" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconKey: React.FC<IconProps> = (p) => <Icon {...p}><circle cx="6" cy="7" r="4" stroke="currentColor" strokeWidth="1.2"/><path d="M9.5 10l5 5M12 12.5l1.5 1.5M11 11.5l1.5 1.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconUser: React.FC<IconProps> = (p) => <Icon {...p}><circle cx="8" cy="5" r="3" stroke="currentColor" strokeWidth="1.2"/><path d="M2 15c0-3.314 2.686-5 6-5s6 1.686 6 5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconGitCommit: React.FC<IconProps> = (p) => <Icon {...p}><circle cx="8" cy="8" r="2.5" stroke="currentColor" strokeWidth="1.2"/><line x1="1" y1="8" x2="5.5" y2="8" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/><line x1="10.5" y1="8" x2="15" y2="8" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconTag: React.FC<IconProps> = (p) => <Icon {...p}><path d="M1 1h6l7 7-6 6-7-7V1z" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><circle cx="4.5" cy="4.5" r="1" fill="currentColor"/></Icon>;
export const IconCode: React.FC<IconProps> = (p) => <Icon {...p}><polyline points="5,4 1,8 5,12" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><polyline points="11,4 15,8 11,12" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><line x1="9" y1="2" x2="7" y2="14" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconDownload: React.FC<IconProps> = (p) => <Icon {...p}><path d="M8 1v9M5 7l3 3 3-3" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/><path d="M2 12v2h12v-2" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/></Icon>;
export const IconCopy: React.FC<IconProps> = (p) => <Icon {...p}><rect x="5" y="5" width="9" height="9" rx="1" stroke="currentColor" strokeWidth="1.2"/><path d="M5 5V4a1 1 0 011-1h6a1 1 0 011 1v1M2 11V3a1 1 0 011-1h6" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconChevronRight: React.FC<IconProps> = (p) => <Icon {...p}><polyline points="6,4 10,8 6,12" stroke="currentColor" strokeWidth="1.4" fill="none" strokeLinejoin="round"/></Icon>;
export const IconChevronDown: React.FC<IconProps> = (p) => <Icon {...p}><polyline points="4,6 8,10 12,6" stroke="currentColor" strokeWidth="1.4" fill="none" strokeLinejoin="round"/></Icon>;
export const IconPlus: React.FC<IconProps> = (p) => <Icon {...p}><line x1="8" y1="2" x2="8" y2="14" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/><line x1="2" y1="8" x2="14" y2="8" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/></Icon>;
export const IconX: React.FC<IconProps> = (p) => <Icon {...p}><line x1="3" y1="3" x2="13" y2="13" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/><line x1="13" y1="3" x2="3" y2="13" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/></Icon>;
export const IconCheck: React.FC<IconProps> = (p) => <Icon {...p}><polyline points="2,8 6,12 14,4" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinejoin="round" strokeLinecap="round"/></Icon>;
export const IconLock: React.FC<IconProps> = (p) => <Icon {...p}><rect x="3" y="7" width="10" height="8" rx="1" stroke="currentColor" strokeWidth="1.2"/><path d="M5 7V5a3 3 0 016 0v2" stroke="currentColor" strokeWidth="1.2"/></Icon>;
export const IconGlobe: React.FC<IconProps> = (p) => <Icon {...p}><circle cx="8" cy="8" r="6.5" stroke="currentColor" strokeWidth="1.2"/><ellipse cx="8" cy="8" rx="3" ry="6.5" stroke="currentColor" strokeWidth="1.2"/><line x1="1.5" y1="6" x2="14.5" y2="6" stroke="currentColor" strokeWidth="1.2"/><line x1="1.5" y1="10" x2="14.5" y2="10" stroke="currentColor" strokeWidth="1.2"/></Icon>;
export const IconPackage: React.FC<IconProps> = (p) => <Icon {...p}><path d="M1 4l7-3 7 3v8l-7 3-7-3V4z" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><polyline points="1,4 8,7 15,4" stroke="currentColor" strokeWidth="1.2" fill="none"/><line x1="8" y1="7" x2="8" y2="15" stroke="currentColor" strokeWidth="1.2"/></Icon>;
export const IconStar: React.FC<IconProps> = (p) => <Icon {...p}><polygon points="8,1 10,6 15,6.5 11.5,10 12.5,15 8,12.5 3.5,15 4.5,10 1,6.5 6,6" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/></Icon>;
export const IconExternalLink: React.FC<IconProps> = (p) => <Icon {...p}><path d="M7 2H2v12h12V9" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/><path d="M10 1h5v5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/><line x1="6" y1="10" x2="14" y2="2" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconAlert: React.FC<IconProps> = (p) => <Icon {...p}><path d="M8 1L1 13h14L8 1z" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><line x1="8" y1="6" x2="8" y2="9" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/><circle cx="8" cy="11.5" r="0.8" fill="currentColor"/></Icon>;
export const IconDiff: React.FC<IconProps> = (p) => <Icon {...p}><line x1="3" y1="4" x2="13" y2="4" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/><line x1="3" y1="8" x2="10" y2="8" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/><line x1="3" y1="12" x2="13" y2="12" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconMenu: React.FC<IconProps> = (p) => <Icon {...p}><line x1="2" y1="4" x2="14" y2="4" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/><line x1="2" y1="8" x2="14" y2="8" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/><line x1="2" y1="12" x2="14" y2="12" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/></Icon>;
export const IconBranch: React.FC<IconProps> = (p) => <Icon {...p}><circle cx="4" cy="4" r="2" stroke="currentColor" strokeWidth="1.2"/><circle cx="4" cy="13" r="2" stroke="currentColor" strokeWidth="1.2"/><circle cx="12" cy="7" r="2" stroke="currentColor" strokeWidth="1.2"/><path d="M4 6v5M4 6C4 9 12 9 12 7" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinecap="round"/></Icon>;
export const IconShield: React.FC<IconProps> = (p) => <Icon {...p}><path d="M8 1L2 4v5c0 3.5 2.5 5.9 6 7 3.5-1.1 6-3.5 6-7V4L8 1z" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/></Icon>;
export const IconEye: React.FC<IconProps> = (p) => <Icon {...p}><path d="M1 8s2.5-5 7-5 7 5 7 5-2.5 5-7 5-7-5-7-5z" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><circle cx="8" cy="8" r="2" stroke="currentColor" strokeWidth="1.2"/></Icon>;
export const IconClock: React.FC<IconProps> = (p) => <Icon {...p}><circle cx="8" cy="8" r="6.5" stroke="currentColor" strokeWidth="1.2"/><path d="M8 4.5v4l2.5 2" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/></Icon>;
export const IconBell: React.FC<IconProps> = (p) => <Icon {...p}><path d="M8 1a5 5 0 015 5v3l1.5 2.5H1.5L3 9V6a5 5 0 015-5z" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><path d="M6.5 13.5a1.5 1.5 0 003 0" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconLink: React.FC<IconProps> = (p) => <Icon {...p}><path d="M6 10a3 3 0 004.24 0l2-2A3 3 0 008 3.76L7 4.76" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/><path d="M10 6a3 3 0 00-4.24 0l-2 2A3 3 0 006 12.24L7 11.24" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconMail: React.FC<IconProps> = (p) => <Icon {...p}><rect x="1" y="3" width="14" height="10" rx="1" stroke="currentColor" strokeWidth="1.2" fill="none"/><polyline points="1,4 8,9 15,4" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/></Icon>;
export const IconLogout: React.FC<IconProps> = (p) => <Icon {...p}><path d="M6 14H2V2h4" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/><polyline points="10,5 14,8 10,11" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><line x1="6" y1="8" x2="14" y2="8" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconSun: React.FC<IconProps> = (p) => <Icon {...p}><circle cx="8" cy="8" r="3" stroke="currentColor" strokeWidth="1.2"/><path d="M8 1v2M8 13v2M1 8h2M13 8h2M3.22 3.22l1.42 1.42M11.36 11.36l1.42 1.42M3.22 12.78l1.42-1.42M11.36 4.64l1.42-1.42" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></Icon>;
export const IconMoon: React.FC<IconProps> = (p) => <Icon {...p}><path d="M13 9A6 6 0 117 3a5 5 0 006 6z" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/></Icon>;
export const IconFolder: React.FC<IconProps> = (p) => <Icon {...p}><path d="M1 4a1 1 0 011-1h4l2 2h6a1 1 0 011 1v7a1 1 0 01-1 1H2a1 1 0 01-1-1V4z" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/></Icon>;
export const IconFile: React.FC<IconProps> = (p) => <Icon {...p}><path d="M3 1h7l4 4v10H3V1z" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/><polyline points="10,1 10,5 14,5" stroke="currentColor" strokeWidth="1.2" fill="none" strokeLinejoin="round"/></Icon>;
