---
name: Build, Test, and Dockerize on PR
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./... -v

    - name: Build application
      run: go build -o hades ./cmd/hades
